### ISSUE TITLE
Add names to services prior to executing the service factory

### ISSUE THREAD

**Issue by SgtFlame** [aethosio/aethos-container#3]
Currently the only way to get the name of a service is by creating it.  I would like to be able to get the name of the service prior to executing the service factory.

**Comment by gruntcoder** [comment]
I added this as part of my refactor.  See [this commit](https://github.com/aethosio/aethos-container/commit/6e684ef48b2b3917d8719a46523105517e9a78dc)

**Comment by gruntcoder** [comment]
This is ready for verification; I don't know how to transition to that state.

**Comment by SgtFlame** [comment]
Looks pretty good, but you might want to update README.md.  I'll incorporate ZenHub with this repo and set up the swim lanes and I'll do a full code review tonight.

**Comment by gruntcoder** [comment]
Fixed the README.md file with updated examples.  See cf48c00ced32d087df2e45837a5e4a0940da5f57.

**Comment by SgtFlame** [comment]
Looks good, sorry for the delay.
